// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Swagger.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class OrderDto
    {
        /// <summary>
        /// Initializes a new instance of the OrderDto class.
        /// </summary>
        public OrderDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OrderDto class.
        /// </summary>
        public OrderDto(System.Guid? id = default(System.Guid?), System.Guid? customerId = default(System.Guid?), IList<OrderItemOutputModel> items = default(IList<OrderItemOutputModel>), System.DateTime? created = default(System.DateTime?), System.DateTime? modified = default(System.DateTime?))
        {
            Id = id;
            CustomerId = customerId;
            Items = items;
            Created = created;
            Modified = modified;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customerId")]
        public System.Guid? CustomerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "items")]
        public IList<OrderItemOutputModel> Items { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "created")]
        public System.DateTime? Created { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modified")]
        public System.DateTime? Modified { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "total")]
        public System.Double Total { get; set; }
    }
}
